name: Test Go

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.x

    - name: go mod tidy
      run: go mod tidy

    - name: go vet
      run: go vet

    - name: go test
      run: go test -v ./...
